[package]
name = "carburetor"
version = "0.1.0"
edition = "2024"

[dependencies]
carburetor-macro = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
diesel = { workspace = true, optional = true, features = [
    "postgres",
    "chrono",
] }
anyhow = { workspace = true }

[features]
default = ["dep:diesel"]
backend = ["carburetor-macro/backend"]
